services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client-chatbot
    ports:
      - "3000:3000"
    env_file: ./.env
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - bot-client
    restart: always

networks:
  bot-client:
    driver: bridge